### ISSUE TITLE
why the j in range(seq_len//2)? why note j in range(seq_len) ?

### ISSUE THREAD

**Issue by sherlockhoatszx** [SwordYork/simplified-deeplearning#1]
```
def generate_data(nb_samples,seq_len,feature_len):
    for i in range(nb_samples):
        for j in range(seq_len//2):
            X[i,j] = dataset[i*seq_len+j*s:i*seq_len+j*s+feature_len]
            # predict next s element
            Y[i,j] = dataset[i*seq_len+j*s+s:i*seq_len+j*s+feature_len+s]
    return X, Y
```

in this code , if the parameter became large, it will  range error:could not broadcast input array from shape (69) into shape (76)
if the 

feature_length = 76
seq_length = 10
s = 24
len(dataset)=1869
nb_samples =176

**Comment by sherlockhoatszx** [comment]
and one more thing ,with that half zeros ,the loss greatly decrease! that is magical...

**Comment by SwordYork** [comment]
Sorry for my late reply. I haven't noticed this issue until yesterday.

First, in my test, set 
```
feature_length = 76
seq_length = 10
```
won't raise the error, but the predict result is awful because of the short `seq_length`.
I think `s` should be calculated as `s = feature_length // 2`, that is 38 (not 24) in this case.

Then I think `j` could be set to `range(seq_len)`, I have forgot why I set it to `range(seq // 2)`.
It is a quick demonstration, and I just make it work.
I'm sorry for the dirty code.
